language: rust
sudo: false
rust:
- stable
- beta
- nightly
os:
- linux
- osx
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo

script: cargo test --all

before_deploy:
- cargo build --release
- $TRAVIS_BUILD_DIR/.travis/make_wasm.sh
deploy:
- provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: evaltrees-wasm/dist
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_RUST_VERSION = nightly
  skip-cleanup: true
- provider: releases
  api_key: $GITHUB_TOKEN
  file: target/release/evaltrees
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true
