language: rust
sudo: false
rust:
- stable
- beta
- nightly
os:
- linux
- osx
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo

script: cargo test --all

before_deploy:
- cargo build --release
- $TRAVIS_BUILD_DIR/.travis/make_wasm.sh
deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file: target/release/evaltrees
  skip_cleanup: true
  on:
    tags: true
