language: rust
sudo: false
rust:
- stable
- beta
- nightly
os:
- linux
- osx
matrix:
  fast_finish: true
cache: cargo

script: cargo test --all

before_deploy: $TRAVIS_BUILD_DIR/.travis/before_deploy.sh
deploy:
- provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: web/dist
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_RUST_VERSION = nightly
  skip-cleanup: true
- provider: releases
  api_key: $GITHUB_TOKEN
  file: evaltrees-${TRAVIS_OS_NAME}.tar.gz
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true
