[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
description = "A simple term-rewriting interpreter that displays intermediate expressions."
license = "Apache-2.0/MIT"
name = "evaltrees"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
human-panic = "1.0.0"
lalrpop-util = "0.15.2"
lazy_static = "1.0.1"
linefeed = "0.5.0"
log = "0.4.1"
regex = "1.0.0"
stderrlog = "0.4.0"
structopt = "0.2.8"
symbol = "0.1.1"
linked_hash_set = "0.1.2"

[build-dependencies]
lalrpop = "0.15.2"

[[bin]]
name = "evaltrees"
path = "src/bin/cli/main.rs"
