[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
description = "A WASM library wrapping evaltrees."
license = "Apache-2.0/MIT"
name = "evaltrees-wasm"
version = "0.0.1"

[dependencies]
evaltrees = { path = ".." }

[lib]
crate-type = ["cdylib"]
